# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kjSdpmgWmG9IQUdrAxCz_DHdpyD45npD
"""

import pandas as pd
df = pd.read_csv('sample_data/california_housing_train.csv')
df[df['population']<501]['median_house_value'].agg(['mean'])

df[df['population']==df['population'].min()]['households'].agg(['max'])